#!/usr/bin/env python

import sys

from rqt_servicebot_pan_tilt.pan_tilt import PanTilt
from rqt_gui.main import Main

plugin = 'rqt_servicebot_pan_tilt'
main = Main(filename=plugin)
sys.exit(main.main(standalone=plugin))
