#!/usr/bin/env python

import sys

from rqt_servicesim_score.servicesim_score import ServicesimScore
from rqt_gui.main import Main

plugin = 'rqt_servicesim_score'
main = Main(filename=plugin)
sys.exit(main.main(standalone=plugin))
