# This simulates the interaction the robot would have with
# a guest when dropping them off, such as:
# "Ok, guest, we've reached your destination. Good bye!"

# Guest name
string guest_name

---

# True if guest understood and stopped following
bool success
