# Request empty for now, these could be useful information to manage
# multi-robot situations but are not relevant right now
# string robot_name
# geometry_msgs/Pose robot_current_pose
---
geometry_msgs/Pose pick_up_location
std_msgs/ColorRGBA guest_clothes_color
string guest_name
