# Request empty for now, these could be useful information to manage
# multi-robot situations but are not relevant right now
# string robot_name
# geometry_msgs/Pose robot_current_pose
---
# Placeholder: this will be changed to the room name
geometry_msgs/Pose pick_up_location
# Placeholder: this will be changed to the room name
geometry_msgs/Pose drop_off_location
# Placeholder: this will be changed to RFID
string guest_name
